[2025-10-17T09:10:21.874+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.soda_scan manual__2025-10-17T09:10:15.608680+00:00 [queued]>
[2025-10-17T09:10:21.883+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.soda_scan manual__2025-10-17T09:10:15.608680+00:00 [queued]>
[2025-10-17T09:10:21.883+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-17T09:10:21.895+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): soda_scan> on 2025-10-17 09:10:15.608680+00:00
[2025-10-17T09:10:21.902+0000] {standard_task_runner.py:57} INFO - Started process 145 to run task
[2025-10-17T09:10:21.906+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'soda_scan', 'manual__2025-10-17T09:10:15.608680+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpap10ebjv']
[2025-10-17T09:10:21.910+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask soda_scan
[2025-10-17T09:10:21.959+0000] {task_command.py:416} INFO - Running <TaskInstance: csv_etl_pipeline.soda_scan manual__2025-10-17T09:10:15.608680+00:00 [running]> on host 0c9ee2dc6164
[2025-10-17T09:10:22.030+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T09:10:15.608680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T09:10:15.608680+00:00'
[2025-10-17T09:10:22.032+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T09:10:22.033+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'soda scan -d ***_pg -c /opt/***/dags/soda/configuration.yml /opt/***/dags/soda/checks.yml']
[2025-10-17T09:10:22.046+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T09:10:23.019+0000] {subprocess.py:93} INFO - [09:10:23] Soda Core 3.5.6
[2025-10-17T09:10:23.097+0000] {subprocess.py:93} INFO - [09:10:23] Counting invalid without valid or invalid specification does not make sense. ("invalid_count(price) = 0" @ line=9,col=5 in /opt/***/dags/soda/checks.yml)
[2025-10-17T09:10:23.100+0000] {subprocess.py:93} INFO - [09:10:23] Scan summary:
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23] 5/6 checks PASSED:
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23]     games in ***_pg
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23]       row_count > 0 [PASSED]
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23]       missing_count(game) = 0 [PASSED]
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23]       duplicate_count(urlgame) = 0 [PASSED]
[2025-10-17T09:10:23.101+0000] {subprocess.py:93} INFO - [09:10:23]     prices in ***_pg
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23]       missing_count(price) = 0 [PASSED]
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23]       invalid_count(price) = 0 [PASSED]
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23] 1/6 checks FAILED:
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23]     prices in ***_pg
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23]       row_count = 0 [FAILED]
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23]         check_value: 3
[2025-10-17T09:10:23.102+0000] {subprocess.py:93} INFO - [09:10:23] Oops! 1 failures. 0 warnings. 0 errors. 5 pass.
[2025-10-17T09:10:23.346+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-10-17T09:10:23.355+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-17T09:10:23.359+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=csv_etl_pipeline, task_id=soda_scan, execution_date=20251017T091015, start_date=20251017T091021, end_date=20251017T091023
[2025-10-17T09:10:23.370+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task soda_scan (Bash command failed. The command returned a non-zero exit code 2.; 145)
[2025-10-17T09:10:23.403+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-17T09:10:23.426+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
